name: manav_s_application6
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cached_network_image: ^3.2.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_material_pickers: ^3.3.0
  flutter_rounded_date_picker: ^3.0.2
  flutter_svg: ^1.1.6
  fluttertoast: ^8.2.1
  get: ^4.6.5
  intl: ^0.17.0
  syncfusion_flutter_datepicker: ^21.1.39
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
